package mybatis.doa;


import java.util.List;
import mybatis.model.Actor;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ActorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTOR
     *
     * @mbg.generated Mon Mar 20 21:59:27 EET 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTOR
     *
     * @mbg.generated Mon Mar 20 21:59:27 EET 2017
     */
    int insert(Actor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTOR
     *
     * @mbg.generated Mon Mar 20 21:59:27 EET 2017
     */
    Actor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTOR
     *
     * @mbg.generated Mon Mar 20 21:59:27 EET 2017
     */
    List<Actor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTOR
     *
     * @mbg.generated Mon Mar 20 21:59:27 EET 2017
     */
    int updateByPrimaryKey(Actor record);
}